/**
 * Aurora Launch — TypeScript interfaces (auto-generated from Pydantic v2).
 *
 * Generated by aurora-launch-export-ts v0.1.0-b05.
 * DO NOT EDIT MANUALLY. Regenerate via: `aurora-launch-export-ts`.
 *
 * Source schemas: src/aurora_launch/schemas/
 */


/** Bundle manifest — SSoT for ZIP container, per ADR-002. */
export interface BundleManifest {
  manifest_version?: string;
  schema_version?: string;
  aurora_app?: string;
  aurora_app_version: string;
  min_app_version: string;
  created_at: string;
  last_modified: string;
  project_id: string;
  revision?: number;
  files?: Record<string, BundleFileEntry>;
  integrity_check?: "strict" | "warn" | "disabled";
  compression?: "store" | "deflate";
  aurora_launch_schema_version?: string | null;
  aurora_launch_migration_history?: Record<string, string>[];
}

/** Per-file metadata in manifest.files. */
export interface BundleFileEntry {
  sha256: string;
  size_bytes: number;
  schema_version?: string | null;
}

/** Канонический формат forecast.json — v1. */
export interface ForecastJsonV1 {
  version?: "1";
  horizon_weeks: number;
  granularity?: "monthly" | "weekly";
  engine_mode?: "pure_transfer" | "transfer_with_bias_check" | "ols_with_proxy_priors" | "bayesian_with_proxy_priors";
  methodology_signature?: string;
  n_recipient?: number;
  weekly_points: ForecastPoint[];
  warnings?: string[];
  anchors?: RecipientAnchorsPayload | null;
  spend_plan?: Record<string, number[]> | null;
  coverage_target?: number;
  seed?: number;
  produced_at?: string | null;
}

/** Одна точка прогноза. `week_index` — period-index (для monthly granularity */
export interface ForecastPoint {
  week_index: number;
  point: number;
  ci_lower: number;
  ci_upper: number;
}

/** Поля RecipientAnchors в форме, пригодной для JSON-bundle. */
export interface RecipientAnchorsPayload {
  market_size: number;
  market_size_cv?: number;
  planned_share_trajectory: number[];
  distribution_trajectory: number[];
  pricing_index: number;
  elasticity: number;
  seasonality?: number[] | null;
}

/** Aggregates Aurora Launch–specific bundle metadata. */
export interface AuroraLaunchBundleMetadata {
  schema_version?: string;
  aurora_launch_version?: string | null;
  proxy_brand_metadata?: ProxyBrandMetadata | null;
}

/** Per PROXY_INTAKE_PROTOCOL.md Шаг 3 — anonymization invariants. */
export interface AnonymizationDetails {
  synchronized_random_factor: number;
  period_shift_months: number;
  brand_name_replaced?: boolean;
  manufacturer_removed?: boolean;
}

/** Abstract contract for plug-in ProxyDataSource. */
export interface FormatAdapterContract {
  adapter_id: string;
  adapter_version: string;
  schema_version: string;
  sample_files_glob: string[];
  canonical_record_mapping: Record<string, string>;
  detected_signatures?: string[];
}

/** Aurora Launch–specific proxy metadata (B1 ManifestV3Launch field). */
export interface ProxyBrandMetadata {
  proxy_code: string;
  similarity_dimensions: SimilarityDimensionScores;
  similarity_score: number;
  verdict: "High" | "Medium" | "Low" | "Insufficient";
  inflation_factor: number;
  intake_workflow_version?: string;
  anonymization_applied: AnonymizationDetails;
}

/** Single proxy brand entry (B2 §4.4.4). */
export interface ProxyEntry {
  proxy_brand_name: string;
  proxy_brand_code: string;
  category_l1: string;
  category_l2: string;
  category_l3: string;
  pricing_tier: "ECONOMY" | "MAINSTREAM" | "PREMIUM" | "LUXURY";
  brand_size: "LEADER" | "CHALLENGER" | "NICHE";
  distribution: "NATIONAL" | "REGIONAL" | "NICHE";
  media_maturity: "ALWAYS_ON" | "PULSING" | "PROMO_DRIVEN" | "DORMANT";
  lifecycle: "NEW" | "GROWING" | "MATURE" | "DECLINING";
}

/** 6+2 dimension similarity scores (per SIMILARITY_FRAMEWORK §1). */
export interface SimilarityDimensionScores {
  category_l1_match: number;
  category_l2_match: number;
  category_l3_match: number;
  pricing_tier_match: number;
  brand_size_match: number;
  distribution_match: number;
  media_maturity_match: number;
  lifecycle_match: number;
  weights_used?: Record<string, number>;
}

/** Specification for synthetic corpus project generation. */
export interface SyntheticProjectSpec {
  seed: number;
  category_l3: "FMCG_food.snacks_savoury" | "FMCG_food.snacks_sweet" | "FMCG_food.dairy_yogurt" | "FMCG_beverage.beverage_carbonated" | "FMCG_beverage.beverage_juice" | "FMCG_beverage.beverage_energy" | "OTC_pharma.OTC_cold_flu" | "OTC_pharma.OTC_pain" | "Cosmetics.skincare_premium" | "Cosmetics.haircare_premium" | "Telecom.telecom_b2c_mobile" | "Banking.banking_retail" | "awareness.brand_awareness_only" | "cross_category.cross_l1_edge";
  variant: "baseline" | "high_seasonality" | "volatile" | "low_data" | "cross_category_edge";
  n_weeks?: number;
  n_channels?: number;
  pricing_tier?: "ECONOMY" | "MAINSTREAM" | "PREMIUM" | "LUXURY";
  brand_size?: "LEADER" | "CHALLENGER" | "NICHE";
  distribution?: "NATIONAL" | "REGIONAL" | "NICHE";
  media_maturity?: "ALWAYS_ON" | "PULSING" | "PROMO_DRIVEN" | "DORMANT";
  lifecycle?: "NEW" | "GROWING" | "MATURE" | "DECLINING";
}
