"""TypeScript interface auto-generation from Aurora Launch Pydantic schemas (B1).

Generates TS interfaces from Pydantic v2 models for frontend (B2 sprint
Tauri+Svelte UI). Outputs к `frontend/src/types/aurora-launch-schema.ts`
or specified path.

Usage:
    aurora-launch-export-ts --output ./frontend/src/types/aurora-launch-schema.ts

Maps Pydantic types to TypeScript:
- str → string
- int / float → number
- bool → boolean
- list[X] → X[]
- dict[K, V] → Record<K, V>
- Optional[X] → X | null
- Literal[...] → union types
- Pydantic models → interfaces
- BaseModel subclasses → recursive interfaces

Limitations (Phase B+ improvements):
- No generic types support (TypeVar)
- No discriminated unions
- No JSON Schema features (regex patterns become comments only)
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any, Literal, Union, get_args, get_origin

import click
from pydantic import BaseModel

from aurora_launch import __version__


def _python_type_to_ts(py_type: Any, model_registry: dict[str, type[BaseModel]]) -> str:
    """Map Python type annotation к TypeScript type expression."""
    # Handle None / NoneType
    if py_type is type(None):
        return "null"

    # Handle string types directly
    if py_type is str:
        return "string"
    if py_type is int or py_type is float:
        return "number"
    if py_type is bool:
        return "boolean"
    if py_type is bytes:
        return "string"  # base64 в JSON serialization

    origin = get_origin(py_type)

    # Handle Optional[X] = Union[X, None]
    if origin is Union:
        args = get_args(py_type)
        non_none = [a for a in args if a is not type(None)]
        has_none = type(None) in args
        if len(non_none) == 1:
            base = _python_type_to_ts(non_none[0], model_registry)
            return f"{base} | null" if has_none else base
        # General union
        parts = [_python_type_to_ts(a, model_registry) for a in args]
        return " | ".join(parts)

    # Handle Literal[...]
    if origin is Literal:
        args = get_args(py_type)
        parts = []
        for a in args:
            if isinstance(a, str):
                parts.append(f'"{a}"')
            elif isinstance(a, bool):
                parts.append("true" if a else "false")
            else:
                parts.append(str(a))
        return " | ".join(parts)

    # Handle list[X] / List[X]
    if origin is list:
        inner = get_args(py_type)[0]
        return f"{_python_type_to_ts(inner, model_registry)}[]"

    # Handle dict[K, V]
    if origin is dict:
        args = get_args(py_type)
        if len(args) == 2:
            k = _python_type_to_ts(args[0], model_registry)
            v = _python_type_to_ts(args[1], model_registry)
            return f"Record<{k}, {v}>"
        return "Record<string, unknown>"

    # Handle Pydantic BaseModel subclass
    if isinstance(py_type, type) and issubclass(py_type, BaseModel):
        model_registry[py_type.__name__] = py_type
        return py_type.__name__

    # Fallback: any
    return "unknown"


def _model_to_ts_interface(
    model: type[BaseModel],
    model_registry: dict[str, type[BaseModel]],
) -> str:
    """Generate TypeScript interface for Pydantic model."""
    name = model.__name__
    lines = [f"export interface {name} {{"]

    # Add docstring as JSDoc if present
    if model.__doc__:
        first_line = model.__doc__.strip().split("\n")[0]
        lines.insert(0, f"/** {first_line} */")

    fields = model.model_fields
    for field_name, field_info in fields.items():
        ts_type = _python_type_to_ts(field_info.annotation, model_registry)
        # Mark optional if default is не PydanticUndefined
        is_optional = field_info.is_required() is False
        opt_marker = "?" if is_optional else ""
        # Add description as inline comment if present
        desc = field_info.description or ""
        comment = f"  /** {desc} */\n" if desc else ""
        lines.append(f"{comment}  {field_name}{opt_marker}: {ts_type};")

    lines.append("}")
    return "\n".join(lines)


def generate_ts_interfaces(models: list[type[BaseModel]]) -> str:
    """Generate complete TypeScript module с all interfaces."""
    header = f"""/**
 * Aurora Launch — TypeScript interfaces (auto-generated from Pydantic v2).
 *
 * Generated by aurora-launch-export-ts v{__version__}.
 * DO NOT EDIT MANUALLY. Regenerate via: `aurora-launch-export-ts`.
 *
 * Source schemas: src/aurora_launch/schemas/
 */
"""

    # Build registry — start с input models, expand recursively as types resolved
    model_registry: dict[str, type[BaseModel]] = {m.__name__: m for m in models}
    interfaces: list[str] = []
    rendered: set[str] = set()

    # Iteratively expand registry until stable
    while True:
        before_size = len(model_registry)
        for model in list(model_registry.values()):
            if model.__name__ not in rendered:
                interfaces.append(_model_to_ts_interface(model, model_registry))
                rendered.add(model.__name__)
        if len(model_registry) == before_size:
            break

    return header + "\n\n" + "\n\n".join(interfaces) + "\n"


@click.command()
@click.option(
    "--output",
    type=click.Path(path_type=Path),
    default=Path("frontend/src/types/aurora-launch-schema.ts"),
    help="Output TypeScript file path.",
)
@click.option(
    "--print",
    "print_only",
    is_flag=True,
    help="Print to stdout instead of writing file.",
)
@click.version_option(version=__version__)
def main(output: Path, print_only: bool) -> None:
    """Auto-generate TypeScript interfaces from Aurora Launch Pydantic schemas."""
    # Import all public models — registry will expand recursively
    from aurora_launch.engines.bundle_manifest import BundleManifest, BundleFileEntry
    from aurora_launch.schemas import (
        AnonymizationDetails,
        AuroraLaunchBundleMetadata,
        FormatAdapterContract,
        ProxyBrandMetadata,
        ProxyEntry,
        SimilarityDimensionScores,
        SyntheticProjectSpec,
    )
    from aurora_launch.schemas.forecast_bundle import (
        ForecastJsonV1,
        ForecastPoint,
        RecipientAnchorsPayload,
    )

    models: list[type[BaseModel]] = [
        # Bundle / manifest contracts (engines layer)
        BundleManifest,
        BundleFileEntry,
        # Forecast bundle (etap 1.3)
        ForecastJsonV1,
        ForecastPoint,
        RecipientAnchorsPayload,
        # Aurora Launch schemas
        AuroraLaunchBundleMetadata,  # composition root
        AnonymizationDetails,
        FormatAdapterContract,
        ProxyBrandMetadata,
        ProxyEntry,
        SimilarityDimensionScores,
        SyntheticProjectSpec,
    ]

    ts_module = generate_ts_interfaces(models)

    if print_only:
        sys.stdout.write(ts_module)
        return

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(ts_module, encoding="utf-8")
    click.secho("✓ ", fg="green", nl=False)
    click.echo(f"Generated TypeScript interfaces: {output}")
    interface_count = ts_module.count("export interface")
    click.echo(
        f"  Models: {len(models)} root + {interface_count - len(models)} dependencies "
        f"= {interface_count} interfaces total"
    )


if __name__ == "__main__":
    main()
